#!/usr/bin/env bash
# script that will display information about subdomains

check_sub_domains() {

	SUBDOMAINS='www lb-01 web-01 web-02'

	if [ -z "$1" ]; then
		exit
	fi

	if [ -z "$2" ]; then
		echo "$SUBDOMAINS" | awk -v domain="$1"\
		'BEGIN { RS=" " }
		{split($0,ARR," ");
		cmd = "dig " ARR[1]"."domain " | grep -A1 \"ANSWER SECTION:\" | tail -n1";
		system(cmd)
		close(cmd)}' | awk\
		'{
		split($0, DOMS, ".");
		print "The subdomain " DOMS[1] " is a " $4 " record and points to " $5}'
	else
		dig "$2.$1" | grep -A1 "ANSWER SECTION:" | tail -n1 | awk\
		'{
		split($0, DOMS, ".");
		print "The subdomain " DOMS[1] " is a " $4 " record and points to " $5}'
	fi
}
check_sub_domains "$1" "$2"
