#!/usr/bin/env bash
# Bash script that Install nginx on my web-01 server and requirements
apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
service nginx start
