#!/usr/bin/env bash
# Configure my Nginx server so that /redirect_me
# is redirecting to my youtube page.
sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/@murendwaratshitimba permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
