#!/usr/bin/env bash
# task #0 optimized script automated fix
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx start
