#!/usr/bin/env bash
# This script displays a statement indefinitely
# Requirements: In between each iteration of the loop, add a sleep 2

while true; do
    echo "To infinity and beyond"
    sleep 2
done