#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
#   "bad luck from China" for the 4th iteration
#   "bad luck from Japan" for the 9th iteration
#   "bad luck from Italy" for the 17th loop iteration

count=0

while [ $count -le 19 ]
do
  echo "$count"
  case $count in
    "3") echo "bad luck from China";;
    "8") echo "bad luck from Japan";;
    "16") echo "bad luck from Italy";;
  esac
  (( count++ ))
done